# start with hidden files on
default_flags = "h"

# custom keybinds
[[verbs]]
key = "ctrl-q"
execution = ":quit"

[[verbs]]
key = "left"
execution = ":parent"

[[verbs]]
key = "right"
execution = ":focus"

#[[verbs]]
#key = "enter"
#execution = "cd"


# [skin]
default = "rgb(25,25,25)"
