# export ZDOTDIR="$HOME/.config/zsh/" > /etc/zsh/zshenv
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

##Custom Keybinds ##
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

## Custom Aliases ##

alias zshhist='micro ~/.local/state/zsh/history'
alias zshenv='micro  ~/.config/zsh/.zshenv'
alias zshrc='micro ~/.config/zsh/.zshrc'
alias hist-clear='echo "" > ~/.local/state/zsh/history & exec $SHELL -l'
alias ytdlp="yt-dlp -f 'ba' -x --no-mtime -o '~/Downloads/Songs/%(title)s.%(ext)s' "
alias setkeyboardworkman='setxkbmap us workman'
alias setkeyboardus='setxkbmap us'
alias scrcpy='prime-run scrcpy -b 16M -Sw --max-fps=30 -m 2048'
alias doasedit='doas micro'
#alias glava='glava -d &'


## END OF FILE #################################################################
# Lines configured by zsh-newuser-install
HISTFILE=~/.local/state/zsh/history
HISTSIZE=1000
SAVEHIST=500
bindkey -e

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/kris/.config/zsh/.zshrc'

autoload -Uz compinit
compinit
compinit -d "$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION"
# End of lines added by compinstall

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# Move .p10k.zsh into ~/.config/zsh first
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# Autosuggestions
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

unsetopt nomatch

# URL-quote-magic shenanigans
# autoload -U url-quote-magic bracketed-paste-magic
# zle -N self-insert url-quote-magic
# zle -N bracketed-paste bracketed-paste-magic

# pasteinit() {
#   OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
#   zle -N self-insert url-quote-magic 
# }
# pastefinish() {
#   zle -N self-insert $OLD_SELF_INSERT
# }
# zstyle :bracketed-paste-magic paste-init pasteinit
# zstyle :bracketed-paste-magic paste-finish pastefinish

# ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(bracketed-paste)

# The rest of the plugins
source ~/.config/zsh/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/zsh-shift-select/zsh-shift-select.zsh

source /home/kris/.config/broot/launcher/bash/br
